export const login = {
  '.login-body': {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#e9e9e9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  '.login-card': {
    display: 'block',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'Poppins',
    boxShadow: '2px 8px 35px rgba(0, 0, 0, 0.05)',
    borderRadius: '10px',
    padding: '40px 60px',
    backgroundColor: '#fff',
  },
  '.login-box': {
    w: '90%',
  },
  '.login-heading': {
    color: 'brand.50',
    fontSize: '30px',
    justifyContent: 'flex-start',
    fontWeight: '700',
    fontFamily: 'Poppins',
    mb: '4',
    textAlign: 'left',
    w: '100%',
    alignItems: 'flex-start',
  },
  '.login-text': {
    display: 'block',
  },
  '.login-firstText': {
    color: 'brand.100',
    mb: '4',
    fontWeight: '500',
    lineHeight: '1.7',
    alignItems: 'flex-start',
  },
  '.login-secondText': {
    color: 'brand.100',
    fontWeight: '500',
    lineHeight: '1.7',
    mt: '4',
    display: 'block',
    alignItems: 'flex-start',
  },
  '.login-email-error': {
    color: 'brand.300',
    width: '90%',
    position: 'relative',
    top: 6,
  },
  '.login-input': {
    bg: 'brand.200',
    fontFamily: 'Poppins',
    display: 'block',
    borderRadius: '4px',
    border: '1px solid #f7f8f9',
    height: '44px',
    textIndent: '15px',
    outline: 'none',
    padding: '8px',
    mb: 2,
  },
  '.login-email-box': {
    position: 'relative',
    mb: 7,
    mt: -3,
  },
  '.login-input-show-hide-img': {
    position: 'absolute',
    top: 2,
    right: '29px',
    zIndex: 1,
  },
  '.login-button': {
    w: '100%',
    mt: 4,
    color: '#000',
    h: '44px',
    fontFamily: 'Poppins',
  },
  '.login-footer': {
    mt: 4,
    fontSize: '10px',
    textAlign: 'center',
  },
}
